import os

from dicionarios import cadastrarCliente
######################################
#####      Projeto PySweet       #####
######################################

resp = ''
while resp != '0':
    os.system('clear')
    print("############################################")
    print("######       Projeto PySweet       ######")
    print("############################################")
    print("#####      1 - Módulo Cadastrar        #####")
    print("#####      2 - Módulo Pesquisar        #####")
    print("#####      3 - Módulo Atualizar        #####")
    print("#####      4 - Módulo Deletar          #####")
    print("#####      5 - Módulo Relatório        #####")
    print("#####      6 - Módulo Informações      #####")
    print("#####      0 - Sair                    #####")
    resp = input("##### Escolha sua opção: ")

    if resp == '1':
        print()
        print("############################################")
        print("#####         Módulo Cadastrar          ####")
        print("############################################")
        print("#####   1 - Cadastrar Cliente          #####")
        print("#####   2 - Cadastrar Venda            #####")
        print("#####   3 - Cadastrar Produto          #####")
        print("#####   0 - Sair                       #####")
        print()
        op_cadas = input("Tecle <ENTER> para continuar...")

        if op_cadas == '1':
          os.system('clear')
          print("############################################")
          print("#####           Cadastra Aluno         #####")
          print("############################################")
          print()
          nome = input("##### Nome: ")
          clientes.update({1: nome})
          print()
          telefone = input("##### Telefone: ")
          print()
          email = input("##### Email: ")
          print()
          endereço = input("##### Endereço: ")
    elif resp == '2':
        print()
        print("############################################")
        print("#####          Módulo Pesquisar         ####")
        print("############################################")
        print("#####   1 - Pesquisar Cliente          #####")
        print("#####   2 - Pesquisar Venda            #####")
        print("#####   3 - Pesquisar Produto          #####")
        print("#####   0 - Sair                       #####")
        print()
        input("Tecle <ENTER> para continuar...")
    elif resp == '3':
        print()
        print("############################################")
        print("#####         Módulo Atualizar          ####")
        print("############################################")
        print("#####   1 - Atualizar Cliente          #####")
        print("#####   2 - Atualizar Venda            #####")
        print("#####   3 - Atualizar Produto          #####")
        print("#####   0 - Sair                       #####")
        print()
        input("Tecle <ENTER> para continuar...")
    elif resp == '4':
        print()
        print("############################################")
        print("#####           Módulo Deletar          ####")
        print("############################################")
        print("#####   1 - Deletar Cliente            #####")
        print("#####   2 - Deletar Venda              #####")
        print("#####   3 - Deletar Produto            #####")
        print("#####   0 - Sair                       #####")
        print()
        input("Tecle <ENTER> para continuar...")
    elif resp == '5':
        print()
        print("############################################")
        print("#####   Você está no Módulo Relatório   ####")
        print("############################################")
        print("#####   1 - Produtos mais vendidos     #####")
        print("#####   2 - Produtos menos vendidos    #####")
        print("#####   3 - Produtos com menor estoque #####")
        print("#####   4 - Maiores compradores        #####")
        print("#####   5 - Datas que mais vendem      #####")
        print("#####   0 - Sair                       #####")
        print()
        input("Tecle <ENTER> para continuar...")
    elif resp == '6':
        print()
        print("############################################")
        print("#####  Você está no Módulo Informações  ####")
        print("############################################")
        print()
        print("##### Projeto de Gestão de uma Fábrica de doces   ####")
        print("##### Equipe de desenvolvimento:                  ####")
        print("##### Diana Rodrigues @dianarodrigues3            ####")
        print("##### Flavius Gorgônio @flgorgonio                ####")
        print("##### Licença Pública Geral GNU                   ####")
        print("##### www.gnu.org/licenses/gpl.html               ####")
        print()
        input("Tecle <ENTER> para continuar...")


print()
print("Você encerrou o programa!")
print("Até logo!")
